### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by wkailiu** [lukesherman/hdi_downscaling_mosaiks#1]
Your work is exciting!
but I am not very sure,  where to download the file `int/ADM2_to_GDL_link/int_file_adm2_polygons_linked_to_GDL_adm1.p` used in
[code/analysis/shapefile_crosswalk_creation/hierarchially_link_adm2_and_adm1_shapefiles.ipynb](https://github.com/lukesherman/hdi_downscaling_mosaiks/tree/master/code/analysis/shapefile_crosswalk_creation/hierarchially_link_adm2_and_adm1_shapefiles.ipynb)

**Comment by lukesherman** [comment]
Hello! Thank you for flagging this issue. I have not included this file in the GitHub repository as it is large and I assumed few users would be interested in it.

That said, I have included the python code needed to generate this file. It should not take too long to create this crosswalk using this code: https://github.com/lukesherman/hdi_downscaling_mosaiks/blob/master/code/analysis/shapefile_crosswalk_creation/hierarchially_link_adm2_and_adm1_shapefiles.ipynb

Alternatively, I can find a way to send you this file.

Thanks! I'm going to close this issue, but feel free to contact with me additional questions.
